(defun lispfuncs()
	(format t "```~%")
	(with-open-file (stream "lispfuncs.lisp")
		(do ((line (read-line stream nil) (read-line stream nil))) ((null line)) 
		(write-line line)))
	(format t "```")
(values))
